# Generated by Django 4.2.6 on 2024-03-21 01:23

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to=main.models.to_path)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.element')),
                ('date', models.DateTimeField()),
                ('lieux', models.CharField(default='', max_length=1000)),
            ],
            bases=('main.element',),
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.element')),
                ('roles', models.CharField(default='', max_length=1000)),
                ('poles', models.CharField(default='', max_length=1000)),
            ],
            bases=('main.element',),
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.element')),
                ('membres', models.CharField(default='', max_length=1000)),
            ],
            bases=('main.element',),
        ),
    ]
