# Generated by Django 5.0 on 2024-03-22 19:35

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="info_1",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="info_1_title",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="info_2",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="info_2_title",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="element",
            name="rating",
            field=models.IntegerField(default=98),
        ),
        migrations.AlterField(
            model_name="element",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=main.models.to_path
            ),
        ),
    ]
